version: '3.3'

services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     env_file:
       - docker-compose-db.env

   wordpress:
     depends_on:
       - db
     image: wordpress:php7.4-apache
     volumes:
      - './wp-content/plugins:/var/www/html/wp-content/plugins'
     ports:
       - "8000:80"
     restart: always
     env_file:
       - docker-compose-wordpress.env
     
volumes:
    db_data: {}