version: '3.3'

services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd01
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: P@ssw0rd02

   wordpress:
     depends_on:
       - db
     image: wordpress:php7.4-apache
     volumes:
      - './wp-content/plugins:/var/www/html/wp-content/plugins'
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress 
       WORDPRESS_DB_PASSWORD: P@ssw0rd02
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DEBUG: '1'
volumes:
    db_data: {}